build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"
  amd64: "ghcr.io/home-assistant/amd64-base:latest"
  armhf: "ghcr.io/home-assistant/armhf-base:latest"
  armv7: "ghcr.io/home-assistant/armv7-base:latest"
  i386: "ghcr.io/home-assistant/i386-base:latest"
args:
  BUILD_ARCH: "{arch}"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Klereo Pool Manager"
  org.opencontainers.image.description: "Klereo pool management integration for Home Assistant"
  org.opencontainers.image.source: "https://github.com/JonBasse/klereo-ha-addon"
  org.opencontainers.image.licenses: "GPL-3.0"
